version: '3.7'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - todoist-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    networks:
      - todoist-network
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ default port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

networks:
  todoist-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
